-- MySQL Script generated by MySQL Workbench
-- Sun May 15 14:20:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `sobre_mi` VARCHAR(280) NOT NULL,
  `domicilio` VARCHAR(140) NULL,
  `ocupacion_actual` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `url_imagen_perfil` VARCHAR(140) NULL,
  `url_imagen_portada` VARCHAR(140) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`experiencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `nombre_empresa` VARCHAR(45) NULL,
  `url_logo_empresa` VARCHAR(140) NULL,
  `descripcion` VARCHAR(200) NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_experiencia_persona_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`educacion` (
  `id` INT NOT NULL,
  `institucion` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `promedio` VARCHAR(45) NULL,
  `anio_inicio` VARCHAR(4) NOT NULL,
  `anio_fin` VARCHAR(4) NULL,
  `url_logo_inst` VARCHAR(140) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_educacion_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`skill` (
  `id` INT NOT NULL,
  `porcentaje` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_skill_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_skill_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`skill_logos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`skill_logos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url_logo` VARCHAR(140) NULL,
  `descripcion` VARCHAR(45) NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`, `skill_id`),
  INDEX `fk_skill_logos_skill1_idx` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_skill_logos_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `portfolio`.`skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(45) NOT NULL,
  `url_imagen` VARCHAR(140) NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `link_proyecto` VARCHAR(140) NULL,
  `anio_realizado` VARCHAR(4) NOT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_proyecto_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`redes_sociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`redes_sociales` (
  `id` INT NOT NULL,
  `url_perfil_linkedin` VARCHAR(100) NOT NULL,
  `url_perfil_github` VARCHAR(100) NOT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_redes_sociales_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_redes_sociales_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
